name: mixtape
services:
  database:
    image: mariadb
    container_name: mixtape-mariadb-01
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=mixtape

  phpmyadmin:
    image: phpmyadmin
    container_name: mixtape-phpmyadmin-01
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=database
