version: '3.3'
name: tsradio
services:
  database:
    image: mariadb
    container_name: mariadb-02
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=tsradio

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-02
    restart: always
    depends_on:
      - database
    ports:
      - "8443:80"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=database