export enum ErrorCodes {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CHANNEL_NOT_FOUND = 'CHANNEL_NOT_FOUND',
  CHANNEL_SLUG_ALREADY_EXISTS = 'CHANNEL_SLUG_ALREADY_EXISTS',
  // Auth/OIDC error codes
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_GRANT = 'INVALID_GRANT',
  INVALID_CLIENT = 'INVALID_CLIENT',
  INVALID_SCOPE = 'INVALID_SCOPE',
  UNSUPPORTED_GRANT_TYPE = 'UNSUPPORTED_GRANT_TYPE',
  INVALID_REQUEST = 'INVALID_REQUEST',
}
